spring:
  h2:
    console:
      enabled: true
  jpa:
    database-platform: "org.hibernate.dialect.H2Dialect"
  datasource:
    url: "jdbc:h2:mem:testdb"
    driver-class-name: "org.h2.Driver"
    username: "sa"
    password: ""
